shellcheck improvements + openvpn sock

diff --git a/scripts/peering-bgp b/scripts/peering-bgp
--- a/scripts/peering-bgp
+++ b/scripts/peering-bgp
@@ -31,23 +31,19 @@ EOF
 }
 
 reset_config () {
-    rm -rf $bird_routes
-    rm -rf $bird_filters
+    rm -rf "$bird_routes"
+    rm -rf "$bird_filters"
 }
 
-remove_ip_rules () {
+
+remove_all_ip_rules () {  # {{{
     table=$1
     while ip $minus6 rule show | grep "$table:" > /dev/null ; do
-        ip $minus6 rule del pref $table
+        ip $minus6 rule del pref "$table"
     done
 }
+# }}}
 
-add_ip_rules () {
-    table=$1
-    cat $prefix_db | while read pfx ; do
-        ip $minus6 rule add from $pfx table $table pref $table
-    done
-}
 
 test $EUID -eq 0 || die "The BIRD BGP daemon requires root access."
 test $# -ge 1 || usage
@@ -72,37 +68,36 @@ test $# -ge 1 || usage
 
 case $1 in
 cli)
-    test -S $bird_sock || die "error [BIRD control socket not found]"
-    $birdc_exec -s $bird_sock
+    test -S "$bird_sock" || die "error [BIRD control socket not found]"
+    $birdc_exec -s "$bird_sock"
     ;;
 start)
-    test -S $bird_sock && die "error [BIRD control socket exists]"
+    test -S "$bird_sock" && die "error [BIRD control socket exists]"
     reset_config
-    mkdir -p $bird_routes
-    mkdir -p $bird_filters
-    remove_ip_rules $kernel_table
-    add_ip_rules $kernel_table
-    $bird_exec -c $bird_cfgfile -s $bird_sock
+    mkdir -p "$bird_routes"
+    mkdir -p "$bird_filters"
+    remove_all_ip_rules "$kernel_table"
+    $bird_exec -c "$bird_cfgfile" -s "$bird_sock"
     ;;
 status)
-    test -S $bird_sock || term "BIRD is down"
-    echo "show protocols" | $birdc_exec -s $bird_sock
+    test -S "$bird_sock" || term "BIRD is down"
+    echo "show protocols" | "$birdc_exec" -s "$bird_sock"
     ;;
 stop)
-    if [ -S $bird_sock ] ; then
-        if ! $(echo "down" | $birdc_exec -s $bird_sock > /dev/null) ;  then
+    if [ -S "$bird_sock" ] ; then
+        if ! echo "down" | "$birdc_exec" -s "$bird_sock" > /dev/null ;  then
             echo "BIRD control socket in bad state, deleting."
         fi
-        rm -f $bird_sock
+        rm -f "$bird_sock"
     fi
-    remove_ip_rules $kernel_table
+    remove_all_ip_rules "$kernel_table"
     reset_config
     ;;
 adv)
     test $# -ge 2 || usage
     mux=$2
-    test ${mux2dev[$mux]:-unset} != "unset" || die "error [unknown mux: $mux]"
-    echo "show route export $mux" | $birdc_exec -s $bird_sock
+    test "${mux2dev[$mux]:-unset}" != "unset" || die "error [unknown mux: $mux]"
+    echo "show route export $mux" | $birdc_exec -s "$bird_sock"
     ;;
 *)
     usage
diff --git a/scripts/peering-openvpn b/scripts/peering-openvpn
--- a/scripts/peering-openvpn
+++ b/scripts/peering-openvpn
@@ -3,9 +3,11 @@ set -eu
 
 usage () {
     cat <<-EOF
-usage: $0 status|up mux|down mux
+usage: $0 status|log mux|up mux|down mux
 
 status      Show the status of configured OpenVPN tunnels.
+
+log mux     Show log file for mux.
 
 up mux      Bring tunnel to mux up.
 
@@ -18,57 +20,63 @@ EOF
 mux_status_check() {
     local mux=$1
     local dev=${mux2dev[$mux]:-unset}
-    test $dev != "unset" || die "error [mux $mux unknown]"
-    local pidfn="$varrun/$dev.pid"
-    if [ ! -s $pidfn ] ; then
+    test "$dev" != unset || die "error [mux $mux unknown]"
+    if ! echo quit | socat - "UNIX:var/$mux.sock" &> /dev/null ; then
+        rm -f "$varrun/$mux.pid"
+        rm -f "$varrun/$mux.sock"
+        rm -f "$varrun/$mux.updown"
         mstat="down"
         return
     fi
-    if ! kill -0 $(cat $pidfn) &> /dev/null ; then
-        echo "deleting $pidfn: cannot send signal"
-        rm $pidfn
-        mstat="down"
-        return
-    fi
-    local statfn="$varrun/$dev.status"
-    if [ ! -s $statfn ] ; then
-        mstat="down"
+    local statfn="$varrun/$mux.updown"
+    if [ ! -s "$statfn" ] ; then
+        echo "OpenVPN status files in inconsistent state [$statfn missing]"
+        mstat="up 0.0.0.0 ::1 [$statfn missing]"
     else
-        mstat=$(head -n 1 $statfn)
+        mstat=$(head -n 1 "$statfn")
     fi
 }
 
+if ! which socat > /dev/null ; then die "PEERING requires the socat tool" ; fi
 test $# -ge 1 || usage
 test $EUID -eq 0 || die "OpenVPN requires root access."
 
 declare -A mux2dev
-while read mux dev ; do
+while read -r mux dev ; do
     mux2dev[$mux]=$dev
-done < $mux2dev_db
+done < "$mux2dev_db"
 
 case $1 in
 up)
     test $# -ge 2 || usage
     mux=$2
-    mux_status_check $mux
+    mux_status_check "$mux"
     if [[ $mstat =~ ^up.*$ ]] ; then term "tunnel $mux already up" ; fi
-    if ! openvpn --cd $progdir --config $openvpn_cfgs/$mux.conf ; then
+    if ! openvpn --cd "$progdir" --config "$openvpn_cfgs/$mux.conf" ; then
         die "openvpn did not start correctly, please check logs"
     fi
     ;;
 down)
     test $# -ge 2 || usage
     mux=$2
-    mux_status_check $mux
+    mux_status_check "$mux"
     if [[ $mstat =~ ^down$ ]] ; then term "tunnel $mux already down" ; fi
     dev=${mux2dev[$mux]}
-    kill -SIGINT $(cat $varrun/$dev.pid)
-    rm -f $varrun/$dev.pid
-    rm -f $varrun/$dev.status
+    echo "signal SIGTERM" | socat - "UNIX:var/$mux.sock" > /dev/null
+    rm -f "$varrun/$mux.pid"
+    rm -f "$varrun/$mux.sock"
+    rm -f "$varrun/$mux.updown"
+    ;;
+log)
+    test $# -ge 2 || usage
+    mux=$2
+    mux_status_check "$mux"
+    echo "$mux ${mux2dev[$mux]} $mstat"
+    cat "$varrun/$mux.log"
     ;;
 status)
-    for mux in ${!mux2dev[@]} ; do
-        mux_status_check $mux
+    for mux in "${!mux2dev[@]}" ; do
+        mux_status_check "$mux"
         echo "$mux ${mux2dev[$mux]} $mstat"
     done | sort
     ;;
